### ISSUE TITLE
Registry key not found

### ISSUE THREAD

**Issue by jhwuser** [Banaanhangwagen/WINHELLO2hashcat#2]
What is Registry.Registry.RegistryKeyNotFoundException: Registry key not found: ROOT/Policy

**Comment by Banaanhangwagen** [comment]
Please provide the exact command you typed, and the exact output.

**Comment by jhwuser** [comment]
Input:
`python WINHELLO2hashcat.py --system '/media/user/Kinesis/Data/Cipher/*****/SYSTEM' --security '/media/user/Kinesis/Data/Cipher/*****/SAM' --cryptokeys '/media/user/Kinesis/Data/Cipher/*****/Keys/' --ngc '/media/user/Kinesis/Data/Cipher/*****/Ngc/' --masterkey '/media/user/Kinesis/Data/Cipher/*****/User/'`

Output:
`Traceback (most recent call last):
  File "/media/user/Kinesis/App/WINHELLO2hashcat/WINHELLO2hashcat.py", line 272, in <module>
    lsa_secrets = reg.get_lsa_secrets(args.security, args.system)
  File "/home/heart/.local/lib/python3.10/site-packages/dpapick3/registry.py", line 101, in get_lsa_secrets
    currentKey = self.get_lsa_key(security)
  File "/home/heart/.local/lib/python3.10/site-packages/dpapick3/registry.py", line 69, in get_lsa_key
    rev = eater.Eater(r.open("Policy\\PolRevision").value("(default)").value())
  File "/home/heart/.local/lib/python3.10/site-packages/Registry/Registry.py", line 442, in open
    return RegistryKey(self._regf.first_key()).find_key(path)
  File "/home/heart/.local/lib/python3.10/site-packages/Registry/Registry.py", line 357, in find_key
    return self.subkey(immediate).find_key(future)
  File "/home/heart/.local/lib/python3.10/site-packages/Registry/Registry.py", line 319, in subkey
    raise RegistryKeyNotFoundException(self.path() + "\\" + name)
Registry.Registry.RegistryKeyNotFoundException: Registry key not found: ROOT\Policy
`

**Comment by Banaanhangwagen** [comment]
Please double check your command.
The `SECURITY` hive is needed, not the `SAM` hive.

**Comment by jhwuser** [comment]
python WINHELLO2hashcat.py --system '/media/user/Kinesis/Data/Cipher/00001/SYSTEM' --security 
'/media/user/Kinesis/Data/Cipher/00001/SECURITY' --cryptokeys '/media/user/Kinesis/Data/Cipher/00001/Keys/' --ngc '/media/user/Kinesis/Data/Cipher/00001/Ngc/' --masterkey '/media/user/Kinesis/Data/Cipher/00001/User/'

Traceback (most recent call last):
  File "/media/user/Kinesis/App/WINHELLO2hashcat/WINHELLO2hashcat.py", line 272, in <module>
    lsa_secrets = reg.get_lsa_secrets(args.security, args.system)
  File "/home/heart/.local/lib/python3.10/site-packages/dpapick3/registry.py", line 101, in get_lsa_secrets
    currentKey = self.get_lsa_key(security)
  File "/home/heart/.local/lib/python3.10/site-packages/dpapick3/registry.py", line 83, in get_lsa_key
    currentKey, self.lsakeys = crypto.decrypt_lsa_key_nt6(lsakey, self.syskey)
  File "/home/heart/.local/lib/python3.10/site-packages/dpapick3/crypto.py", line 226, in decrypt_lsa_key_nt6
    g = "%0x-%0x-%0x-%0x%0x-%0x%0x%0x%0x%0x%0x" % struct.unpack("<L2H8B", keys[off:off + 16])
struct.error: unpack requires a buffer of 16 bytes

**Comment by Banaanhangwagen** [comment]
There is something wrong with the input files you use; 
can you execute the script on a Windows machine, and run it again but with the `--windows [path]` option, in order to exclude typos/wrong copied files?
